config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  mount Ckeditor::Engine => '/ckeditor'
  get 'home/index'

  devise_for :users
  resources :recipes
  mount Commontator::Engine => '/commontator'

  root 'recipes#index'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/commontator_comment.rb
class CommontatorComment < ActiveRecord::Base

  belongs_to :user, foreign_key: :creator, polymorphic: true

end

app/models/content.rb
class Content < ActiveRecord::Base

  has_many :ingredients
  
  validates :name, presence: true

end

app/models/harmful.rb
class Harmful < ActiveRecord::Base

  belongs_to :recipe
  belongs_to :user

  validates :reason, presence: true, if: "is_harmful"

  # Validations
  # Limitation for no. of characters for comment @shweta: Do we need this validation
end

app/models/image.rb
require 'carrierwave/orm/activerecord'
class Image < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader

  belongs_to :associate, polymorphic: true

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

  belongs_to :recipe
  belongs_to :content

  validates :content_id, presence: true

  attr_accessor :content_name

  def content_name=(name)
    self.content = Content.create(name: name)
  end

  def content_name
    self.content.name
  end

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  ratyrate_rateable 'Like'
  acts_as_commontable

  belongs_to :user
  has_many :ingredients
  has_many :harmfuls
  has_many :images, as: :associate

  validates :user, :title, :steps, presence: true
  validates :title, uniqueness: true

  accepts_nested_attributes_for :ingredients
  accepts_nested_attributes_for :images
  # Validations
  # Limitation for no. of characters for description
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ratyrate_rater
  acts_as_commontator

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :recipes
  has_many :harmfuls

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create,:edit,:update]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :collect_recipes, only: [:show, :index]
  
  def index
    @recipe = @recipes.shuffle.first
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      flash[:success] = 'Recipe created Successfully!!'
      redirect_to root_path
    else
      flash[:error] = 'Please resolve following errors!!'
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update_attributes(recipe_params)
      flash[:success] = 'Recipe updated Successfully!!'
      redirect_to root_path
    else
      flash[:error] = 'Please resolve following errors!!'
      render :edit
    end
  end

  def destroy
    if @recipe.destroy
      flash[:success] = 'Recipe deleted Successfully!!'
      redirect_to root_path
    else
      flash[:error] = 'Unable to remove recipe!!'
    end
  end
  
  private
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def collect_recipes
    @recipes = Recipe.all
  end

  def recipe_params
    params.require(:recipe).permit!#(:id, :title, :pre_requirements, :steps, :description, :benifits, images_attributes: [:avatar, :id, :associate_id, :associate_type, :_destroy], ingredients_attributes: [:content_id, :quantity, :_destroy, :description])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-static-top{ role: "navigation" }
  .container-fluid
    .navbar-header
      - if signed_in?
        %button{ class: "navbar-toggle", "data-toggle" => "collapse", "data-target" => "#navcollapse" }
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar 

    = link_to '' do 
      = content_tag(:div, class: "btn", id: "continue") do
        = image_tag('logo3.png', size: '100x40', alt: "Continue")
    .collapse.navbar-collapse.navbar-right#navcollapse
      = render "layouts/navbar_body"

app/views/layouts/_navbar_body.html.haml
%b
  %ul.nav.navbar-nav
    %li= link_to content_tag(:span, "", class: "glyphicon glyphicon-list-alt") + "  Recipes", recipes_url
    - if signed_in?
  
      %li= link_to "New Recipe", new_recipe_path
      %li= link_to content_tag(:span, "", class: "glyphicon glyphicon-log-out") + " Sign Out", destroy_user_session_path, method: :delete
    - else
      %li= link_to "sign_in", new_user_session_path
      %li= link_to "sign_up", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RecipeGuru
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #wrap
      = render 'layouts/navbar'
      .container
        .panel-body
          = render 'shared/flash'
          = yield
          - if ((params["controller"].eql?("recipes") and (["new","edit", "create", "update"].include?params["action"])) or params[:controller].include?('devise'))
            %body{background: asset_url("bg_image2.jpeg")}
          - else
            - img_num = ['3', '5'].shuffle.first 
            %body{background: asset_url("bg_image" + img_num + ".jpeg")}

    #footer
      .container

app/views/recipes/_form.html.haml
.row
  .col-md-3
    .col-md-12
      = f.input :title, label: false, placeholder: 'Title'
    .col-md-12
      = f.input :time, label: false, placeholder: 'Time'
    .col-md-12
      = f.input :description, label: false, placeholder: 'Description'
    .col-md-12
      = f.input :pre_requirements, label: false, placeholder: 'Pre Requirements'
    .col-md-12
  .col-md-9
    = render partial: 'ingredients', locals: {f: f}
    .col-md-12
      %br
      %br
      = f.input :steps, label: 'Recipe', placeholder: 'Enter Steps here', input_html: {class: 'redactor'}, :as => :ckeditor
.row
  = render partial: 'images', locals: {f: f}
%br
%br
%br
.col-md-1
  %label Benifits:
.col-md-5
  = f.input :benifits, input_html: { rows: 4, cols: 6 }, label: false, placeholder: 'Description (if any)'
.col-lg-12
  .pull-right= f.submit class: "btn btn-info"

app/views/recipes/_images.html.haml
.col-md-4
  .col-md-12
    %label Please add images of your recipe:
  .col-md-12
    = f.link_to_add "Add an image", :images, class: "btn btn-danger btn-xs", data: {target: "#images"}
%br
.col-md-7
  #images
    = f.fields_for :images do |image|
      - if image.object.persisted?
        .col-md-3= image_tag image.object.avatar.thumb.url
      - else
        .col-md-12
          .col-md-6
            = image.file_field :avatar
          .col-md-4
            = image.link_to_remove "Remove", class: "btn btn-danger btn-xs"

app/views/recipes/_ingredients.html.haml
.col-md-12
  .col-md-3
    %strong 
      %label Ingredients:
  .col-md-4= f.link_to_add "Add ingredient", :ingredients, class: "btn btn-danger btn-xs", data: {target: "#new_ingredient"}
%br
%br
%br
.col-md-9
  #new_ingredient
  = f.simple_fields_for :ingredients do |ingredient|
    .col-md-4
      = ingredient.association :content, collection: Content.order(:name).collect{|c| ["#{c.name} - #{c.taste}", c.id] } << ["other","other"], label: false, prompt: "Select Ingredient"
    .col-md-3
      = ingredient.input :quantity, label: false, placeholder: 'Quantity'
    .col-md-4
      = ingredient.input :description, input_html: { rows: 1, cols: 6 }, label: false, placeholder: 'Description (if any)'
    .col-md-1
      %br
      = ingredient.link_to_remove "Remove", class: "btn btn-danger btn-xs" unless ingredient.object.persisted?

app/views/recipes/_list.html.haml
%center.h2
  %b Available Recipes
%ul.list-group
  - (@recipes - [@recipe]).each do |recipe|
    %li.list-group-item.recipe-title
      %center= link_to recipe.title.upcase, recipe_path(recipe)
      - unless recipe.images.blank?
        %center= image_tag (recipe.images.first.try(:avatar).try(:thumb).try(:url))

app/views/recipes/_recipe.html.haml
- unless recipe.blank?
  .div
    %center
      %b=recipe.title.try(:capitalize)

    - if recipe.images.count > 0
      #myCarousel.carousel.slide{ "data-ride"=>"carousel" }
        %ol.carousel-indicators
          - recipe.images.count.times do |index|
            - active = 'active' if (index == 0)
            %li{ "data-target" => "#myCarousel", "data-slide-to"=> index, class: active}

        .carousel-inner{role:"listbox"}
          - active = 'active'
          - recipe.images.each do |image|
            %center.item{class: active}= image_tag image.try(:avatar).try(:large).url
            - active = ''


        %a{ class: "left carousel-control", href: "#myCarousel", role:"button", "data-slide"=>"prev"}
          %span{ class:"glyphicon glyphicon-chevron-left", "aria-hidden"=> "true" }
          %span.sr-only Previous
    
        %a{ class: "right carousel-control", href: "#myCarousel", role:"button", "data-slide"=>"prev"}
          %span{ class: "glyphicon glyphicon-chevron-right", "aria-hidden" => "true" }
          %span.sr-only Next
  %br
  %b Time:
  = recipe.time
  %br
  %b Description:
  %p= recipe.description
  %br
  - if recipe.pre_requirements.present?
    %b Pre Requirements:
    %p= recipe.pre_requirements
  %br
  #ingredients
    %b Ingredients:
    - recipe.ingredients.each do |ing|
      = ing.content.name + '-' + ing.quantity + '(' + ing.description + ')'
  %br
  %b Recipe:
  %p= raw(recipe.steps)
  %br
  - if current_user.eql?(@recipe.user)
    %center
      = link_to "Edit", edit_recipe_path(@recipe), class: 'btn btn-primary'
      = link_to "Remove", recipe_path(@recipe), method: :delete, class: 'btn btn-primary'
  .row
  Rate the recipe : 
  = rating_for recipe, "Like", star: 5, disable_after_rate: false
  %br
  = commontator_thread(recipe)

app/views/recipes/edit.html.haml
.container-fluid
  .row.subject
    .col-md-3
      %h3 Edit your recipe
  %br
  = simple_nested_form_for @recipe do |f|
    = render partial: 'form', locals: {f: f}

app/views/recipes/index.html.haml
- if @recipe.present?
  .row
    .col-md-3= render partial: 'list'
    .col-md-8= render partial: 'recipe', locals: {recipe: @recipe}
- else
  Be first to add recipes!! 
  - unless current_user
    Sign up to add recipes !!

app/views/recipes/new.html.haml
.container-fluid
  .row.subject
    .col-md-3
      %h3 Add your recipe
  %br
  = simple_nested_form_for @recipe do |f|
    = render partial: 'form', locals: {f: f}

app/views/recipes/show.html.haml
.row
  .col-md-3= render partial: 'list'
  .col-md-8= render partial: 'recipe', locals: {recipe: @recipe}

app/views/shared/_flash.html.haml
- flash.each do |name, msg|
  - case name
    - when 'success'
      .alert.alert-success
        %a.close{ "data-dismiss" => "alert"}x
        = msg
    - when 'danger'
      .alert.alert-danger
        %a.close{ "data-dismiss" => "alert"}x
        = msg
    - when 'alert'
      .alert.alert-danger
        %a.close{ "data-dismiss" => "alert"}x
        = msg
    - when 'notice'
      .alert.alert-info
        %a.close{ "data-dismiss" => "alert"}x
        = msg
- flash.clear